# Generated by Django 4.1.5 on 2023-03-28 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=9, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'notes_Group',
            },
        ),
        migrations.CreateModel(
            name='NotificationsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_reaction', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('condition', models.CharField(choices=[('POSTPONED', 'POSTPONED'), ('UNFULFILLED', 'UNFULFILLED '), ('COMPLETED', 'COMPLETED')], default='UNFULFILLED', max_length=11)),
            ],
            options={
                'db_table': 'notes_Notifications',
            },
        ),
        migrations.CreateModel(
            name='PlanInfoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('date_completion', models.DateField()),
                ('importance', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('LOW', 'LOW'), ('MIDDLE', 'MIDDLE'), ('HIGH', 'HIGH')], default='UNKNOWN', max_length=8)),
                ('condition', models.CharField(choices=[('OVERDUE', 'OVERDUE'), ('UNFULFILLED', 'UNFULFILLED '), ('COMPLETED', 'COMPLETED'), ('REMOTE', 'REMOTE'), ('RUNNING', 'RUNNING')], default='UNFULFILLED', max_length=11)),
            ],
            options={
                'db_table': 'notes_PlanInfo',
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'notes_Plan',
            },
        ),
        migrations.CreateModel(
            name='ReminderInfoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('date_completion', models.DateField()),
                ('importance', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('LOW', 'LOW'), ('MIDDLE', 'MIDDLE'), ('HIGH', 'HIGH')], default='UNKNOWN', max_length=8)),
                ('condition', models.CharField(choices=[('OVERDUE', 'OVERDUE'), ('UNFULFILLED', 'UNFULFILLED '), ('COMPLETED', 'COMPLETED'), ('REMOTE', 'REMOTE')], default='UNFULFILLED', max_length=11)),
            ],
            options={
                'db_table': 'notes_ReminderInfo',
            },
        ),
        migrations.CreateModel(
            name='ReminderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'notes_Reminder',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDayModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=20)),
                ('condition', models.CharField(choices=[('WORKING', 'WORKING'), ('WEEKEND', 'WEEKEND')], default='WEEKEND', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('execution_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notes_ScheduleDay',
            },
        ),
        migrations.CreateModel(
            name='TimerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_left', models.PositiveBigIntegerField(null=True)),
            ],
            options={
                'db_table': 'notes_Timer',
            },
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(null=True)),
                ('group', models.ManyToManyField(related_name='schedule', to='notes.groupmodel')),
            ],
            options={
                'db_table': 'notes_Schedule',
            },
        ),
    ]
