# Generated by Django 4.1.5 on 2023-03-22 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='group',
            field=models.ManyToManyField(related_name='plan', to='notes.groupmodel'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='notes.planinfomodel'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planinfomodel',
            name='timer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='notes.timermodel'),
        ),
    ]
