# Generated by Django 4.1.5 on 2023-03-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledaymodel',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='notes.schedulemodel'),
        ),
        migrations.AddField(
            model_name='remindermodel',
            name='group',
            field=models.ManyToManyField(related_name='reminder', to='notes.groupmodel'),
        ),
        migrations.AddField(
            model_name='remindermodel',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='notes.reminderinfomodel'),
        ),
        migrations.AddField(
            model_name='remindermodel',
            name='notifications',
            field=models.ManyToManyField(related_name='reminder', to='notes.notificationsmodel'),
        ),
        migrations.AddField(
            model_name='remindermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='group',
            field=models.ManyToManyField(related_name='plan', to='notes.groupmodel'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='notes.planinfomodel'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planinfomodel',
            name='timer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='notes.timermodel'),
        ),
        migrations.AddField(
            model_name='notificationsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
